version: '3.8'

services:

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: smartsure-sqlserver
    environment:
      SA_PASSWORD: "SmartSure@123"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    restart: unless-stopped

  rabbitmq:
    image: rabbitmq:management
    container_name: smartsure-rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    restart: unless-stopped
